### ISSUE TITLE
3.2SectionB的运行时的一些问题

### ISSUE THREAD

**Issue by 2628372574** [idejie/mml-assignment3#29]
一、运行时，出现以下报错
Traceback (most recent call last):
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\training.py", line 116, in <module>
    trainer.valid_epoch()
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\model\trainer.py", line 69, in train_epoch
    for batch_idx, (img_emb, cap, att_mask) in enumerate(loop):
  File "D:\Anaconda3\envs\3.2\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\dataloader.py", line 484, in __iter__
    return self._get_iterator()
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\dataloader.py", line 415, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\dataloader.py", line 1138, in __init__
    w.start()
  File "D:\Anaconda3\envs\3.2\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\3.2\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\3.2\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\3.2\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\3.2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_loader.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\envs\3.2\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Anaconda3\envs\3.2\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

其中，有“AttributeError: Can't pickle local object 'get_loader.<locals>.<lambda>'”，以及根据gpt的解释“在 Windows 系统上使用多进程（multiprocessing）时，Python 无法正确序列化（pickle）DataLoader 中的 collate_fn 函数”，总之是get_loader函数中的collate_fn=lambda b: cl_fn(b, tokenizer)问题

既然不能接受lambda函数，我就把它改成了collate_fn=cl_fn（实际上我不知道这里写成lambda函数和直接传递函数有什么区别）
再尝试运行，又出现了以下第二个错误

二、
Traceback (most recent call last):
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\training.py", line 116, in <module>
    trainer.train_epoch()
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\model\trainer.py", line 69, in train_epoch
    for batch_idx, (img_emb, cap, att_mask) in enumerate(loop):
  File "D:\Anaconda3\envs\3.2\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\dataloader.py", line 1491, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\_utils.py", line 715, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\_utils\worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
    return self.collate_fn(data)
TypeError: cl_fn() missing 1 required positional argument: 'tokenizer'

似乎是cl_fn在被调用的时候少传递了tokenizer这个参数，但是调用它的位置在torch\utils\data\dataloader.py，也就是torch的库...我应该不能去修改torch的代码
于是我修改cl_fn函数，让tokenizer不再作为参数，而是全局变量
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token        
（但这样就没法根据config来调整tokenizer了，只是暂时的解决方案吧）

于是又出现了以下第三个报错
三、
Traceback (most recent call last):
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\training.py", line 115, in <module>
    trainer.train_epoch()
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\model\trainer.py", line 81, in train_epoch
    loss = self.model.train_forward(
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\model\model.py", line 253, in train_forward
    img_mapped = self.mp(img_emb, train_mode=True)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\model\model.py", line 69, in forward
    x = self.transformer_encoder(img_embedded)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\transformer.py", line 511, in forward
    output = mod(
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\transformer.py", line 904, in forward
    + self._sa_block(x, src_mask, src_key_padding_mask, is_causal=is_causal)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\transformer.py", line 918, in _sa_block
    x = self.self_attn(
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\modules\activation.py", line 1368, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "D:\Anaconda3\envs\3.2\lib\site-packages\torch\nn\functional.py", line 6070, in multi_head_attention_forward
    embed_dim == embed_dim_to_check
AssertionError: was expecting embedding dimension of 768, but got 512

其实就是model.py的Mapping类的forward中，        x = self.transformer_encoder(img_embedded)的维度对不上
（在-S s的情况下，expecting embedding dimension of 768, but got 512）
但是按照我的理解，Mapping这个类的作用就是把图像嵌入映射到gpt2的嵌入。。。那他不接受原始的图像嵌入的维度？
那我应该在这个Mapping类中增加一个全连接层把输入数据映射到需求的维度吗（在这里是512到768）

这些问题我也不知道出现会不会是我代码别的部分的实现有误，所以也不知道自己尝试做的这些修改是否合理。。。

**Comment by idejie** [comment]
从最后的错误看，确实是embedding的维度问题，建议使用debug模式，观察一下输入以及网络的维度是否匹配
